// Auto-generated by `prisma init` (Prisma v6). Loads .env.local so Prisma CLI
// commands (db push, db seed, migrate) can resolve DATABASE_URL without a .env file.
import dotenv from "dotenv";
import path from "path";
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
